name: Update Total Active Days

on:
  schedule:
    # Runs automatically every day at midnight (UTC)
    - cron: "0 0 * * *"
  workflow_dispatch: # Allows manual trigger from the GitHub Actions tab

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Python Script
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: python active_days.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "📊 Update Total Active Days" || exit 0
          git push
